### ISSUE TITLE
Dockable Solars Moor Updates

### ISSUE THREAD

**Issue by FireFlyEx** [Freelancer-Sirius-Revival/FLSR#412] opened 2023-02-26 11:03 UTC
Alongside the large ship physics update I will be checking various base models to make sure that they are easily dockable for larger ships. 

First example, **space_factory01.cmp** had the docking points too close to the middle of the model and it caused ships to crash into the base before being able to dock.

_HpDockMountH, HpDockPointH01, HpDockPointH02, HpDockMountI, HpDockPointI01, HpDockPointI02, HpDockMountG, HpDockPointG01, HpDockPointG02_

All of these had to be re-positioned and their orientation fixed to allow a ship to properly dock.

Potential issues:
- I had to do the work with HardCMP because LancerEdit isn't working for me. So there are potential issues?

**Comment by erikroe** [comment] 2023-02-26 23:12
Duplicate of https://github.com/Freelancer-Sirius-Revival/FLSR/issues/412

**Closed by erikroe** 2023-02-26 23:12 UTC
