### ISSUE TITLE
Northern Ice Field of California without Info Card

### ISSUE THREAD

**Issue by erikroe** [Freelancer-Sirius-Revival/FLSR#102] opened 2022-06-11 21:19 UTC
Northern Ice Field of California without Info Card.

**Comment by Caenen** [comment] 2023-08-02 15:35
Cannot reproduce issue, does not appear to be an issue in Vanilla either.

![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/7fa14564-bb97-4e42-bc3b-54dcae5d5ab4)


![grafik](https://github.com/Freelancer-Sirius-Revival/FLSR/assets/79576409/5b008d94-de52-47a5-b7de-5195eda77d2f)

**Comment by Caenen** [comment] 2023-08-11 21:04
We came to the conclusion the reported problem likely happened when object was marked as visited but not actively visited via a rumor exclusively or similar.

**Closed by Caenen** 2023-08-11 21:04 UTC
Labels: enhancement
